org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

# Minecraft版本必须与NeoForge版本一致才能获得有效的构件
minecraft_version=1.21.1
# Minecraft版本范围可以使用任何Minecraft发布版本作为边界
minecraft_version_range=[1.21.1,1.22)
# NeoForge版本必须与Minecraft版本一致
neoforge_version=21.1.125
# NeoForge版本范围
neoforge_version_range=[21.0.42-beta,)
# 加载器版本范围只能使用NeoForge/FML的主要版本作为边界
loader_version_range=[4,)
# 映射频道
mapping_channel=official
# 要从映射频道查询的映射版本
mapping_version=1.21.1

parchment_minecraft_version=1.21
parchment_mappings_version=2024.07.28

# 模组的唯一标识符
mod_id=maid_useful_task
# 模组的可读显示名称
mod_name=maid useful task
# 模组的许可证
mod_license=MIT
# 模组版本
mod_version=1.2.0
# 模组的组ID
mod_group_id=studio.fantasyit
# 模组的作者
mod_authors=
# 模组的描述
mod_description=
